version: "3"

services:
  react-app:
    image: node:16.15.0-alpine
    container_name: react-app-dev
    working_dir: /app
    environment:
      - PATH=/app/node_modules/.bin:$PATH
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command:
      - sh
      - -c
      - |
        npm install
        npm start
